# Generated by Django 5.1.5 on 2025-02-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chat_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='download_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
