# Generated by Django 5.1.5 on 2025-02-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
